services:
  - type: web
    name: expense-tracker-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_NAME
        fromDatabase:
          name: expense-tracker-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: expense-tracker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: expense-tracker-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: expense-tracker-db
          property: host

  - type: web
    name: expense-tracker-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://expense-tracker-backend.onrender.com/api

databases:
  - name: expense-tracker-db
    databaseName: expense_tracker_db
    user: expense_tracker_user 