services:
  - type: web
    name: expense-tracker-api
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: a5f9e31c8b2d7e6412fd89g7h5j3k2l1m
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_q4HTixdL0hDN@ep-late-shape-a5rtlmi5-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: FRONTEND_URL
        value: https://expense-tracker8887735.netlify.app

  - type: web
    name: expense-tracker-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://test-expense-tracker-shhn.onrender.com/api

databases:
  - name: expense-tracker-db
    databaseName: expense_tracker_db
    user: expense_tracker_user 